<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNDoYHIX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNDoYHIX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNDoYHIX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNDoYHIX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNDoYHIX\App_KernelDevDebugContainer([
    'container.build_hash' => 'NDoYHIX',
    'container.build_id' => '791687a9',
    'container.build_time' => 1689931831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNDoYHIX');
